### ISSUE TITLE
interactive shell detection must be done in the handler, not in the initi

### ISSUE THREAD

**Issue by mboisson** [codeandkey/mii#12]
**Describe the bug**
In a typical Slurm cluster, the login node environment will be exported to the job. That means the detection of whether a shell is interactive or not can't be done at "init" time (i.e. in the `bash` or `zsh` script). It must rather be done in the handler (currently in `common`).

**Comment by mboisson** [comment]
Also, checking whether `PS1` is defined is not the canonical way of checking whether a shell is interactive. 
```[[ $- == *i* ]]``` would be the right way

**Comment by codeandkey** [comment]
Thank you @mboisson for the bug report! I've added a runtime interactive shell test which should resolve this issue, please let me know if it works for you.

**Comment by mboisson** [comment]
I commented in the PR directly. I think your implementation will work, but could be simpler.

**Comment by mboisson** [comment]
PR https://github.com/codeandkey/mii/pull/14 addresses this
