### ISSUE TITLE
"module" not found as alternative

### ISSUE THREAD

**Issue by bartoldeman** [codeandkey/mii#19]
**Describe the bug**
When mistyping `module` as `moduel` I get suggested `"modutil", "modutil", "modutil"`, three times, where I expect it only once and also `module`

**To Reproduce**
```
[oldeman@build-node ~]$ moduel load gcc
[mii] moduel not found! Similar commands: "modutil", "modutil", "modutil"
```

**Expected behavior**
```
[mii] moduel not found! Similar commands: "module", "modutil"
```

**Desktop (please complete the following information):**
not relevant

**Smartphone (please complete the following information):**
not relevant

**Comment by bartoldeman** [comment]
I suspect perhaps `mii` doesn't take shell functions into account?

**Comment by codeandkey** [comment]
Thank you for the report @bartoldeman! Yes, Mii is currently unable to index shell functions so the `module` command will be missed. It is definitely possible to remove duplicate suggestions from the output though.

**Comment by codeandkey** [comment]
The duplicate results have been removed in #23, and for now mii will not include shell function completion -- it would likely require a separate index to the module information. Closing this issue.
