### ISSUE TITLE
module autoload message is missing

### ISSUE THREAD

**Issue by kayleanelson** [codeandkey/mii#2]
In the included documentation, it states the researcher will see a response from mii that says `[mii] autoloading <modulename>`. This doesn't appear to be the case in the version of the code that is available on github. Could it be added? It would be useful for our researchers to understand that a module is being loaded for them behind the scenes.

**Comment by codeandkey** [comment]
Whoops -- in the past Mii did output a message before loading modules but it was removed in later versions. Looking back, I agree it should have stayed. Re-added in #3 and I'll redo the documentation soon too.

**Comment by kayleanelson** [comment]
Awesome, thanks!
