### ISSUE TITLE
Support for compiler modules / embedded MODULEPATHs

### ISSUE THREAD

**Issue by codeandkey** [codeandkey/mii#4]
Some modules modify the `MODULEPATH` when loaded, introducing new available modules to load. It is common practice to do this with compiler modules.

Currently Mii will not detect the modifications to the `MODULEPATH` and the partially available modules will not be found.

The analysis process needs to be modified to scan module files for additional `MODULEPATH`s and add them to the search so they can be indexed.

**Comment by JLague** [comment]
I am currently working on implementing this feature.

**Comment by codeandkey** [comment]
@JLague Thank you!

**Comment by mboisson** [comment]
I can imagine this is a hard PR to properly test, but I just want to report that we are currently deploying Mii with this PR on our clusters. While Justin has finish his internship, I am happy to answer questions as best as I can.

**Comment by codeandkey** [comment]
Implemented in #7, closing.
