### ISSUE TITLE
mii 1.0.3 build failed with gcc 9 and above on ubuntu 19 and ubuntu 20

### ISSUE THREAD

**Issue by arm7star** [codeandkey/mii#5]
mii 1.0.3 build failed with gcc 9 and above on ubuntu 19 and ubuntu 20.
"-Werror=format-security" and "-Werror=unused-result" treated security format and unused result as errors.

Build mii 1.0.3 witch gcc 9 and above on ubuntu 19 and ubuntu 20 using make command.
See error below:
src/log.c:36:9: error: format not a string literal and no format arguments [-Werror=format-security]
   36 |         fprintf(stderr, color);

src/modtable.c: In function '_mii_modtable_parse_from':
src/modtable.c:427:5: error: ignoring return value of 'fread', declared with attribute warn_unused_result [-Werror=unused-result]
  427 |     fread(magic_seq, sizeof magic_seq, 1, f);

Is there some commit to fix it? Thank you.

**Comment by codeandkey** [comment]
Hello @arm7star, thank you for identifying this bug. I have pushed 2 additional commits to fix the issue (bf39acf, 3257de3). Please let me know if this fixes the build on your end.

**Comment by arm7star** [comment]
>> 14    src/modtable.c:468:9: error: ignoring return value of 'fread', declared with attribute warn_unused_result [-Werror=unused-result]
>> 18    src/main.c:183:13: error: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Werror=unused-result]

**Comment by codeandkey** [comment]
Glad to hear it is building! I've pushed fixes for the other two errors which will be included in the next release.

**Comment by darmac** [comment]
Hi, may I ask when the new version will release?

**Comment by codeandkey** [comment]
Hi @darmac, the new release has been posted (1.0.4).

**Comment by darmac** [comment]
@code
Got it, thanks so much.
